---
# Install boto3
- name: Install boto3
  pip:
    name: boto3

# Install requests
- name: Install requests
  pip:
    name: requests

# Create worker directory
- name: Create a directory if it does not exist
  file:
    path: /home/ec2-user/worker
    state: directory