---
# Install boto3
- name: Install boto3
  pip:
    name: boto3

# Install requests
- name: Install requests
  pip:
    name: requests

# Create worker directory
- name: Create a directory if it does not exist
  file:
    path: /home/ec2-user/worker
    state: directory

# Copy job worker zip from s3
- name: GET jobworker.zip from s3
  s3:
    bucket: greg-test-ami-job-worker
    object: /jobworker.zip
    dest: /home/ec2-user/worker
    mode: get

# Change ownership of worker directory
- name: Recursively change ownership of a directory
  file:
    path: /home/ec2-user/worker
    state: directory
    recurse: yes
    owner: ec2-user
    group: ec2-user