---

# Ensure all packages have been patched
- name: upgrade all packages
  yum:
    name: "*"
    state: latest

# Install RVM
- name: Import RVM role
  become: yes
  import_role:
    name: rvm.ruby
  vars:
    rvm1_user: ec2-user
    rvm1_bundler_install: True
    rvm1_rubies:
      - 'ruby-2.5.5'
    rvm1_install_path: 'home/ec2-user/.rvm'
    rvm1_install_flags: '--auto-dotfiles  --user-install'

# Installs latest available version of cfn-nag.
- name: Install cfn-nag
  gem:
    name: cfn-nag
    state: latest
  become: true
  become_user: ec2-user