---
- name: Import RVM role
  become: yes
  import_role:
    name: rvm.ruby
  vars:
    rvm1_user: root
    rvm1_rubies:
      - 'ruby-2.5.5'
    rvm1_install_path: '/usr/local/rvm'
    rvm1_install_flags: '--auto-dotfiles'